# Some variables can be in enviroment
# See more https://pkg.go.dev/github.com/kkyr/fig#UseEnv

bot:
  # token: 
  # guild: 
  setup-commands: false
  global-commands: false
  use-mobile-os: true
  debug-log: false

presence-updater:
  enabled: true
  delay: 10s
  presences:
    - state: Online now!

    # - name:
    #   type:
    #   status:
    #   url:
    #   state:
